Tracker:AddItems("items/items.json")
Tracker:AddItems("items/settings.json")

Tracker:AddMaps("maps/maps.json")

ScriptHost:LoadScript("scripts/logic.lua")

Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/settings.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/goalsettings.json")
Tracker:AddLayouts("layouts/wincondition.json")

ScriptHost:LoadScript("scripts/loadlocations.lua")
ScriptHost:LoadScript("scripts/autotracking.lua")

-- TEMP until I can figure out how to actually make something like loadlocations work

Tracker:AddLocations("/locations/SeasideHill.json")
Tracker:AddLocations("/locations/OceanPalace.json")
Tracker:AddLocations("/locations/EggHawk.json")
Tracker:AddLocations("/locations/GrandMetropolis.json")
Tracker:AddLocations("/locations/PowerPlant.json")
Tracker:AddLocations("/locations/TeamFight1.json")
Tracker:AddLocations("/locations/CasinoPark.json")
Tracker:AddLocations("/locations/BingoHighway.json")
Tracker:AddLocations("/locations/RobotCarnival.json")
Tracker:AddLocations("/locations/RailCanyon.json")
Tracker:AddLocations("/locations/BulletStation.json")
Tracker:AddLocations("/locations/EggAlbatross.json")
Tracker:AddLocations("/locations/FrogForest.json")
Tracker:AddLocations("/locations/LostJungle.json")
Tracker:AddLocations("/locations/TeamFight2.json")
Tracker:AddLocations("/locations/HangCastle.json")
Tracker:AddLocations("/locations/MysticMansion.json")
Tracker:AddLocations("/locations/RobotStorm.json")
Tracker:AddLocations("/locations/EggFleet.json")
Tracker:AddLocations("/locations/FinalFortress.json")
Tracker:AddLocations("/locations/EggEmperor.json")
Tracker:AddLocations("/locations/MetalMadness.json")
Tracker:AddLocations("/locations/EmeraldStages.json")